### ISSUE TITLE
adding color to transcripts plot by category

### ISSUE THREAD

**Issue by bioinfonm** [tengfei/ggbio#100]
Hello,

First, thanks for making and maintaining ggbio. I have a de novo genome and a set of transcripts across treatments (pure, early infection, late infection) that are up or down regulated. I used gmap to build a bam and gff file for reading into ggbio.

```
scaff <- readGAlignments("gmap_out_scaffold.bam",=TRUE)
seqinfo(scaff)
txdb <- makeTxDbFromGFF(file="gmap_pure_early.gff", format="gff3")
head(seqlevels(txdb))
```

For plotting I want to show the whole genome. We have it as a single contig. And I want to show where the UTRs, Transcripts, and Genes map to.

```
p0 <- autoplot(scaff, aes(color = strand, fill = strand), facets = strand ~ seqnames)

trans <- transcriptsBy(txdb, "exon")
trans

genes <- exonsBy(txdb, by="gene")
genes

fiveprimeUTR <- fiveUTRsByTranscript(txdb)

p3 <- autoplot(fiveprimeUTR, which=GRanges("scaffold1", IRanges(start=0, end=39000000)),
              names.expr = "gene_id",color = "red")

p4 <- autoplot(trans, which=GRanges("scaffold1", IRanges(start=0, end=39000000)),
               names.expr = "gene_id")

p5 <- autoplot(genes, which=GRanges("scaffold1", IRanges(start=0, end=39000000)),
               names.expr = "gene_id")

tracks(Genome=p0, UTR=p3, Transcripts=p4, Genes=p5, heights = c(3, 1, 2, 1)) + ylab("") +
  theme_tracks_sunset()
```

That will yield this plot, which I think is good so far.

![test_plot](https://user-images.githubusercontent.com/2340132/38958338-36f477de-431a-11e8-9d33-1bed435c020e.png)

I would like to color code the Transcripts by up or down regulated and by treatment. Where in the ggbio pipeline would add this additional data. For a given transcript id like TRINITY_DN2409_c0_g2_i1 I have the up or down and the infection stage. 

Thanks for any advice or help.
ara

**Comment by lawremi** [comment]
If you had an mcols variable representing the up/down and treatment status on the `trans` GRanges`, I think you could map that to a color by passing e.g. `fill=that_variable` to the `autoplot()` call that makes `p4`.

**Comment by lawremi** [comment]
Yes, like `mcols(trans)$foo <- "bar"`.

**Comment by bioinfonm** [comment]
Thanks! That worked well.
