### ISSUE TITLE
Problem with autoplot

### ISSUE THREAD

**Issue by marziacremona** [tengfei/ggbio#107]
Hello, 

I updated ggbio package and now the function `autoplot` gives me the following error:
`Error in min(c(x, xmin), na.rm = TRUE) :  invalid 'type' (list) of argument`

I get the same error both with my own data and the package example.
Here is the package example code:

`library(ggbio)`
`set.seed(1)`
`N <- 1000`
`library(GenomicRanges)`
 `gr <- GRanges(seqnames = `
 `                        sample(c("chr1", "chr2", "chr3"),size = N, replace = TRUE),`
 `                        IRanges(`
`                                       start = sample(1:300, size = N, replace = TRUE),`
`                                       width = sample(70:75, size = N,replace = TRUE)),`
`                         strand = sample(c("+", "-", "*"), size = N, replace = TRUE),`
`                         value = rnorm(N, 10, 3), score = rnorm(N, 100, 30),`
`                         sample = sample(c("Normal", "Tumor"), size = N, replace = TRUE),`
`                         pair = sample(letters, size = N, replace = TRUE))`
`idx <- sample(1:length(gr), size = 50)`
`autoplot(gr[idx])`

And this is the `sessionInfo`
> R version 3.4.0 (2017-04-21)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] GenomicRanges_1.30.3 GenomeInfoDb_1.14.0  IRanges_2.12.0       S4Vectors_0.16.0    
> [5] ggbio_1.26.1         ggplot2_3.0.0        BiocGenerics_0.24.0  BiocInstaller_1.28.0

**Comment by lawremi** [comment]
Please upgrade your R and Bioconductor.
