### ISSUE TITLE
Autoplot example from manual not working

### ISSUE THREAD

**Issue by syouligan** [tengfei/ggbio#115]
Hi there

I have recently tried to reproduce a circle plot using a ggbio script that worked when it was created several months ago however it no longer works. While troubleshooting I have discovered that I cannot run even the simple autoplot command from the manual:

data("CRC", package = "biovizBase")
autoplot(hg19sub, layout = "circle", fill = "gray70")

Error in min(c(x, xmin), na.rm = TRUE) : 
  invalid 'type' (list) of argument

I have been looking through the github issues and can see there are potentially some issues with the author having moved on. I was wondering if these issues are related to that and if ggbio is likely to be usable in the future or is it likely to be discontinued?

Thanks for the fantastic tool, I hope the project continues.

**Comment by lawremi** [comment]
Please post `sessionInfo()`. You'll need the latest Bioconductor to be sure things work with recent versions of ggplot2.

**Comment by syouligan** [comment]
@lawremi Hi Michael,

Rookie error, I have now updated all and all functions are working fine. Sorry for the hassle.

Thanks
