### ISSUE TITLE
Hi! developers! I am using ggbio to plot gene model. Is there a way to plot only genes in gff3? I don't want transcripts in gff3.Thanks!

### ISSUE THREAD

**Issue by chesterlee7246** [tengfei/ggbio#118]

**Comment by lawremi** [comment]
Please show us the code you are currently using. You might be able to just pass `state="reduce"` somewhere.

**Comment by chesterlee7246** [comment]
> 
> 
> Please show us the code you are currently using. You might be able to just pass `stat="reduce"` somewhere.

Here's my code.

library(ggbio)
library(rtracklayer)
library(GenomicFeatures)
library(Rsamtools)
library(GenomicAlignments)
library(VariantAnnotation)

txdb <- makeTxDbFromGFF(file="./Zea_mays.B73_RefGen_v4.43.gff3", format="gff3")
autoplot(txdb, which=GRanges("1", IRanges(175967545, 175999135)), names.expr = "gene_id")

It displays all transcripts in a given region, but i don't want all transcripts, i just need gene. Is there a way to achieve this? Thanks!

**Comment by lawremi** [comment]
I think you can pass `stat="reduce"` to `autoplot()` in this case.

**Comment by chesterlee7246** [comment]
It works, but after i did this, gene id label disappeared.
![图片](https://user-images.githubusercontent.com/36124580/61220420-dedcb180-a748-11e9-94d6-5443f917bb9e.png)

**Comment by lawremi** [comment]
I would need the input data to help further with the label. The transcript direction will go away, since a gene is not a transcript.

**Comment by chesterlee7246** [comment]
OK. Here's my input data.
ftp://ftp.ensemblgenomes.org/pub/plants/release-43/gff3/zea_mays/Zea_mays.B73_RefGen_v4.43.gff3.gz

**Comment by lawremi** [comment]
This should be fixed in version 1.31.3.

**Comment by lawremi** [comment]
I meant version 1.33.1.
