### ISSUE TITLE
Plot CNV graphs over an Ideogram 

### ISSUE THREAD

**Issue by andri90** [tengfei/ggbio#120]
Hello,

I need to create reports that contain two CNV graphs and an Ideogram, for 30 samples.
I have the following code which produces the  CNV graph:

```
one=read.table("$sampleid.chr$chr.$start.signal",sep="\\t")
bmp(filename="$sampleid.chr$chr.$start.$end.CN$cn.bmp",width = 720, height = 720, res=300, pointsize=6)
par(mfrow=c(3,1),las=1,mar=c(4,4.2,1.5,1.3))

a=rep("blue",length(one\$V1))
for(i in 1:length(one\$V1)){
	if(one\$V1[i]>=$start1 & one\$V1[i]<=$end1){
		a[i]="red"
	}
}
plot(one\$V1,one\$V2,pch=20,cex=$cex,ylim=c($lrr_bound,1),ylab="Log R Ratio",xlab="Chr$chr Position ($megabp)",col=a)
title(paste("$sampleid.chr$chr.$start-$end","(CN=$cn)"))
abline(v=c($start1,$end1),col="grey",lty=1,lwd=0.3)
abline(h=0,col="grey",lty=2,lwd=0.3)
plot(one\$V1,one\$V3,pch=20,cex=$cex,ylim=c(0,1),ylab="B Allele Freq",xlab="Chr$chr Position ($megabp)",col=a)
abline(v=c($start1,$end1),col="grey",lty=1,lwd=0.3)
```
![201025100257_R12C02 chr18 73410271 73557030 CN3](https://user-images.githubusercontent.com/51119653/62472613-6e510f80-b79f-11e9-9006-c9f44ec54ae2.jpg)

I would like to add the Ideogram of the respective chromosome below these two plots. I set the command **par(mfrow=c(3,1),las=1,mar=c(4,4.2,1.5,1.3))** for three rows, so that in the last I get the ideogram. 

I visualise the ideogram with this **print(plotIdeogram(genome = "hg19"))** 
![Rplot](https://user-images.githubusercontent.com/51119653/62472354-cb989100-b79e-11e9-85ec-0ef4c2eaa03d.png)
but no matter what I have tried, the ideogram refuses to go under the existing plots, instead it overwrites them. Is it possible to manipulate the Ideogram object to make it follow my layout?

**Comment by lawremi** [comment]
ggbio produces graphics using the grid package, which is different from base graphics. The gridBase package might help you combine them; but I have no experience with it.

**Comment by andri90** [comment]
Thank you @lawremi , this worked great!
