### ISSUE TITLE
Segment not parallel

### ISSUE THREAD

**Issue by blsfoxfox** [tengfei/ggbio#122]
Hi,

I am trying to draw CNV as segment. Here's my code:
 ggbio() +circle(cnv_gr, geom = "segment",color = "black",fill="black",trackWidth =20,radius=60,grid=T,size=1.5,aes(y=Corrected_Copy_Number,yend=Corrected_Copy_Number))+
      circle(genome.ranges, geom = "ideo", fill = "gray70") +
      circle(genome.ranges, geom = "text", aes(label = seqnames), vjust = -1, size = 4)

![image](https://user-images.githubusercontent.com/10779259/72927257-77b54080-3d1b-11ea-9444-1f1402ce1b24.png)

As you can see, some segments are not parallel to its grid.
Could you please help me with that?

Thanks,
LB

**Comment by lawremi** [comment]
Please provide a reproducible example.

**Comment by blsfoxfox** [comment]
I can run it with “rect” so I think it is solved.
