### ISSUE TITLE
Registered S3 method overwritten by 'GGally'

### ISSUE THREAD

**Issue by BatoolMM** [tengfei/ggbio#126]
I'm encountering a strange problem with `ggbio` when I load it, I get this error:

```
Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2
```
Which makes the console stuck forever (left it for over 20 hours but never gets back) in the R console. I tried the same thing on my sister's MacBook and had the same error. 

I used the following to install the packages:
```
BiocManager::install("ggbio")
library(ggbio)
```
To resolve the problem, I re-installed both R, all RFrameworks at least 9 times but still, the same problem occurs after installing `ggbio`. Things go back to normal if I remove `ggbio`.
I use R-4.0.3, with and without RStudio v1.3.

Is it possible that `ggbio` is pulling in an outdated version of `GGally` and overwriting the core functions of `ggplot2` (such as +`.gg`)?

This is `sessionInfo()`:
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3
```
and this for the second machine:
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_4.0.3      tools_4.0.3
```
To replicate the problem:
- reinstall the package with `BiocManager::install('ggbio')`.
- load `ggbio` with `library(ggbio)`.
- then the console will be stuck forever!

I'm really sorry as I posted this problem in Bioconductor help form a week ago but didn't get any solution. I'm stuck with this problem for over 2 weeks and have some analysis that I urgently need to submit.

Thanks,
Batool

**Comment by lawremi** [comment]
Thanks for the report. Unfortunately, I (and probably many others) have been unable to reproduce this. The message from GGally may be a red herring, since that is always emitted. This is the first time I've heard of R locking up when loading a package. The first thought is that it could be something in the methods package, where perhaps you have some old packages installed somewhere (check .libPaths()). But then it's unlikely that the same anomaly would exist on your sister's computer.

**Comment by BatoolMM** [comment]
Thank you @lawremi for your quick reply and Happy New year!
This is also **my first time** seeing R locking up when loading a package! I used 'ggbio' a few months back and it used to work fine! This absolutely has nothing to do with **old packages installed somewhere** because I simply removed all libs in `.libPaths()`, all cache and only installed `BiocManager` and `ggbio`. I lost counts of how many times I did this!
My sister's Mac has no R prior to me installing it. I'm happy to record both Mac's screen showing the same error. I also tried to install the package today in RStudio Cloud but it failed!
**Can I kindly ask you to re-install the package today (on Mac) and then try to load it?**

![Alt Text](https://media.giphy.com/media/I1nwVpCaB4k36/giphy.gif)

**Comment by lawremi** [comment]
Everything works as expected for me, in fresh installs of both R release and devel. It does pause for about 10-20 seconds after it prints the message about GGally, so that's obviously a compute intensive step. Perhaps this is some sort of resource issue?

**Comment by BatoolMM** [comment]
Thank you @lawremi, it could be a resource issue, that's why it pauses. Thanks anyway.
