### ISSUE TITLE
Adding a label.text.angle parameter to rotate Track labels

### ISSUE THREAD

**Issue by matthuska** [tengfei/ggbio#55]
I sometimes use tracks that not very high, which results in the track labels being cut off. It would be very useful to be able to rotate the labels so that they are horizontal.

I put together a basic patch that should hopefully do the trick, and adds a label.text.angle parameter to the tracks() function along with all other necessary code to make it all work, along with documentation. This should allow arbitrary rotation of the labels, rather than only allowing vertical/horizontal orientations.

**Comment by JohnReid** [comment]
Did this ever get incorporated into ggbio? It would be useful for me

**Comment by lawremi** [comment]
I just applied this in devel (1.21.4).

**Comment by JohnReid** [comment]
Thanks
