### ISSUE TITLE
error in autoplot() when set karyogram parameter. 

### ISSUE THREAD

**Issue by wuzefeng-nwsuaf** [tengfei/ggbio#64]
Hi,
i am using the "ggbio" library, it works well.  However, when i used the autoplot function to draw the chromosome positions, it gave error: "error: Unknown parameters: rect.height ". 
my code is :
library(ggbio)              # version:1.18.1
library(rtracklayer)
gr<-import.bed("Desktop/test.bed")
> gr
GRanges object with 5 ranges and 1 metadata column:
      seqnames    ranges strand |        name
         <Rle> <IRanges>  <Rle> | <character>
  [1]     chr1 [ 2,  30]      * |           2
  [2]     chr1 [51, 100]      * |           2
  [3]     chr2 [21,  40]      * |           3
  [4]     chr2 [51,  70]      * |           2
  [5]     chr3 [11,  30]      * |           2

> autoplot(gr,layout="karyogram")
错误: Unknown parameters: rect.height

**Comment by lawremi** [comment]
Best bet for right now is to downgrade your ggplot2 to something < 2.0. I am working on updating ggbio for the new ggplot2, but it will take a while before changes propagate to release.

**Comment by map2085** [comment]
i am having the same problem.  it fails even with the examples on the ggbio  layout_karyogram website

e.g.  the example is: 

autoplot(hg19IdeogramCyto, layout = "karyogram", cytoband = TRUE)

which prints fine.  But if you do:

autoplot(hg19IdeogramCyto, layout = "karyogram" )

Then it throws the same error that  wuzefeng-nwsuaf  reports here.

**Comment by wuzefeng-nwsuaf** [comment]
Yeah, i just downgraded my ggplot2 to a version< 2.0  as suggested by lawremi, but it still give the same error.

**Comment by map2085** [comment]
I concur.  I tried downgrading ggplot2 to 1.0.1 per lawremi's suggestion as well.  But ggbio still throws the same error for the given example.

**Comment by wuzefeng-nwsuaf** [comment]
Yeah,correct @map2085

**Comment by map2085** [comment]
So this is clearly not a problem with ggplots2, but rather with ggbio

**Comment by map2085** [comment]
@wuzefeng-nwsuaf   were you able to find a work-around in the meantime?  downgrading ggplot2 did not solve the problem. nor did downgrading ggbio.  Perhaps both ggplot2 AND ggbio must be downgraded to some common older date/time/version?

**Comment by wuzefeng-nwsuaf** [comment]
No, i haven't yet tried it. It is so boring,hah

**Comment by lawremi** [comment]
Sorry for the delays. Just checked in version 1.18.2 that should address this issue as well as add compatibility with ggplot2 2.0. Will take a while to propagate through the build machines. Please reopen if the issue persists.
