### ISSUE TITLE
autopilot yielding errors with new ggplot

### ISSUE THREAD

**Issue by vnaranbhai** [tengfei/ggbio#65]
Running Ideogram(genome = "hg19")+xlim(generange) yields the following error:
1: `axis.ticks.margin` is deprecated. Please set `margin` property  of `axis.text` instead

Previously this function worked fine and I surmise from reading posts regarding other packages that this may be because the rewrite of ggplot2 last year has changed the way margins are specified. Addition of a command such as + theme(axis.text.x = element_text(margin=margin(5,5,10,5,"pt")),axis.text.y = element_text(margin=margin(5,5,10,5,"pt"))) to the above command doesn't solve the problem so does thethe code within the plotting function in ggbio itself need to be updated?

**Comment by lawremi** [comment]
Should be fixed in Bioc svn (1.19.7).
