### ISSUE TITLE
specifying scale = free for geom_rect

### ISSUE THREAD

**Issue by arjunvadapalli** [tengfei/ggbio#71]
Hi,
   I am trying to get the scale to be specified as "free" and not "fixed" for presenting intervals since the intervals in each chromosome is having a different min and max for intervals in that chromosome. How do I enable that in geom_rect plot in ggbio ?
Thanks
Arjun

**Comment by lawremi** [comment]
Have you tried passing the `scales` argument as documented by `facet_wrap`?

**Comment by arjunvadapalli** [comment]
Thank you for your comment. What I needed was to pass the scales comment via facet_grid and it worked. I had the syntax wrong when I was trying earlier.
