### ISSUE TITLE
it's really hard to install ggbio

### ISSUE THREAD

**Issue by jmzeng1314** [tengfei/ggbio#72]
I don't know what's wrong with it .
So far , I have successfully installed ggbio in my personal computor (R3.2.2,64bit,windows7)
But when I try to install it to my server, **many errors occur !!**
OS-linux,R-3.1

firstly, The error is below: and someone told me that  gridExtra v2.0.0 doesn't export latticeGrob anymore. it's only available in v.0.9.1. 

> Error : object ‘latticeGrob’ is not exported by 'namespace:gridExtra'

So I installed  the older version for gridExtra !! but error again !

> Error in rematchDefinition(definition, fdef, mnames, fnames, signature) :
>   arguments (environment) after '...' in the generic must appear in the method, in the same place at the end of the argument list
> Error : unable to load R code in package 'ggbio'

Then I try to install the older version ggbio: 

```
packageurl <- "http://www.bioconductor.org/packages/2.11/bioc/src/contrib/ggbio_1.6.6.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```

> Error : objects 'matchMatrix', 'elementMetadata', 'elementMetadata<-', 'metadata', 'metadata<-', 'isTRUEorFALSE' are not exported by 'namespace:IRanges'

I search the error log, someone tell me that  **ggbio has not been upgraded to work with the newest ggplot2;**
So I installed the older version , Then try to install ggbio again, but error again !!!

> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
>   namespace 'ggplot2' 1.0.1 is already loaded, but >= 2.0.0 is required

Then I remove the older ggplot ,and install the newest one , Then error again !!!

> Error in rematchDefinition(definition, fdef, mnames, fnames, signature) :
>   arguments (environment) after '...' in the generic must appear in the method, in the same place at the end of the argument list
> Error : unable to load R code in package 'ggbio'
> ERROR: lazy loading failed for package 'ggbio'

Now I am really down, I am very confused about ggbio package.

**Comment by lawremi** [comment]
Which version of R are you using on your server? My guess is that it's old, because the gridExtra issue was fixed last summer. ggbio has been updated to the new version of ggplot2, although not all fixes have made it into release. But the new Bioc release is just around the corner.

**Comment by Nazeeefa** [comment]
Hi, does it work for R version 3.5.1? I tried to install it but doesn't seem to work :/
