### ISSUE TITLE
zoom region not working.

### ISSUE THREAD

**Issue by mbertalan** [tengfei/ggbio#73]
plotIdeogram(hg19IdeogramCyto, "chr1", aspect.ratio = 1/20, zoom.region = c(1e+07,
5e+07))

No zoom region on the plot.

**Comment by CathG** [comment]
Hi
I have ggbio_1.20.1 and same problem, seems to come from last part of function `Ideogram` where `zoom.region` parameter is not passed in the new Ideogram object returned. I modified this part of `Ideogram` function: 
```
new("Ideogram", ggbio(p, data = obj.ori, ...), subchr = subchr, 
     xlabel = xlabel, cytoband = cytoband, color = color, 
     fill = fill, alpha = alpha, zoom.offset = zoom.offset, 
     size = size, aspect.ratio = aspect.ratio, zoom.region=zoom.region)
```
and everything works fine now.

**Comment by mbertalan** [comment]
Fantastic CathG ! It is working. Would be possible to add this modification on the latest ggbio version ?

**Comment by lawremi** [comment]
Thanks for the fix. I applied it to both release and devel. Should appear with version 1.20.2.

**Comment by mbertalan** [comment]
Dear CathG and lawremi,

I have ggbio version 1.20.2 but the zoom regions still not working. How can I make it work ? 

Best,

Marcelo

**Comment by CathG** [comment]
Hi mbertalan, I tried the line of code you put in your first message and got the highlight on the zoom.region as expected (with ggbio 1.20.2). Could you be more specific concerning your problem? Best Regards.

**Comment by mbertalan** [comment]
Dear CathG,

many thanks for looking at so fast. I am sorry, I was a mistake on my code. You are right, it is working. Sorry for the inconvenience.
