### ISSUE TITLE
Naming conflict from importing all of ggplot2 and all of BiocGenerics

### ISSUE THREAD

**Issue by richierocks** [tengfei/ggbio#76]
*ggbio* currently [imports all of *ggplot2* and all of *BiocGenerics*](https://github.com/Bioconductor-mirror/ggbio/blob/master/NAMESPACE#L19L32).

I'm developing a package that depends upon *ggbio*, and when I build my package, I get the warning:

```
Warning: replacing previous import 'ggplot2::Position' by 'BiocGenerics::Position' when loading 'ggbio'
```

Please can you adjust the *ggbio* `NAMESPACE` file to only import the functions from those packages that you actually use.

**Comment by lawremi** [comment]
Should be fixed in devel. I used the new `except=` namespace feature to exclude the `Position` import from ggplot2.
