### ISSUE TITLE
ggbio colors not working properly

### ISSUE THREAD

**Issue by fpbarthel** [tengfei/ggbio#77]
Hi!

I'm having issues specifying colors for ggbio. For example, the following code does not respect colors:

    ggplot() + layout_circle(gr, geom = "ideo", fill = "red", radius = 7, trackWidth = 3) 

Using the data given below, this results in the following. As you can see, the background is black, despite specifying red in the code.
![image](https://cloud.githubusercontent.com/assets/9220167/17299100/7a9a0be6-57d2-11e6-9c30-64b7bbb8fde4.png)

I am using ggplot2_2.1.0 and ggbio_1.18.5 on R 3.2.3

Example data (taken from ggbio docs):

    N = 100
    gr <- GRanges(seqnames = 
                    sample(c("chr1", "chr2", "chr3"),
                           size = N, replace = TRUE),
                  IRanges(
                    start = sample(1:300, size = N, replace = TRUE),
                    width = sample(70:75, size = N,replace = TRUE)),
                  strand = sample(c("+", "-", "*"), size = N, 
                                  replace = TRUE),
                  value = rnorm(N, 10, 3), score = rnorm(N, 100, 30),
                  sample = sample(c("Normal", "Tumor"), 
                                  size = N, replace = TRUE),
                  pair = sample(letters, size = N, 
                                replace = TRUE))
    seqlengths(gr) <- c(400, 500, 700)

**Comment by lawremi** [comment]
Just need to update to latest release.

**Comment by fpbarthel** [comment]
Hi! Thanks for the suggestion but according to biocLite, I am running the latest version of ggbio!

**Comment by lawremi** [comment]
Update your R.

**Comment by fpbarthel** [comment]
Thanks for the suggestion. I had already pursued the "update version" idea several weeks ago to try to fix this but to no result. I work at a large computational lab in MD Anderson and our R version is dependent on the cluster management team to update it, however they say they cannot due to licensing issues with the free version of the R studio web server. Is there any way to fix this issue without updating R?
