### ISSUE TITLE
align genomic features with phylogenetic tree

### ISSUE THREAD

**Issue by GuangchuangYu** [tengfei/ggbio#83]
Hi Tengfei,

In <https://www.biostars.org/p/218591/>, someone asking how to generate the following figure:

![](http://ivanya.com/tmp/2016/1024.tree.png)

I think ggtree with ggbio can work together to do this. After trying out `ggbio`, I get the below figure:

![](https://cloud.githubusercontent.com/assets/626539/19676558/93634b8c-9ac7-11e6-8fe4-6511aa3cf3ee.png)

by the following source code:

```r
library(ggbio)
library(Homo.sapiens)
class(Homo.sapiens)
##
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene

data(genesymbol, package = "biovizBase")
wh <- genesymbol[c("BRCA1", "NBR1")]
wh <- range(wh, ignore.strand = TRUE)
library(biovizBase)
gr.txdb <- crunch(txdb, which = wh)
## change column to  model 
colnames(values(gr.txdb))[4] <- "model"
grl <- split(gr.txdb, gr.txdb$tx_id)
## fake some randome names
set.seed(2016-10-25)
names(grl) <- sample(LETTERS, size = length(grl), replace = TRUE)

library(ggtree)
n <- names(grl) %>% unique %>% length
set.seed(2016-10-25)
tr = rtree(n)
tr$tip.label = sample(unique(names(grl)), n)

ggtree(tr) + geom_tiplab() -> p

grl2 <- grl
names(grl2) <- p$data$y[match(names(grl), p$data$label)]
grl2 <- grl2[order(as.numeric(names(grl2)))]
grl3 <- endoapply(grl2, function(x) {
    x$panel <- 'alignment'
    x$panel <- factor(x$panel, levels=c("TREE", "alignment"))
    x
})

aln <- geom_alignment(grl3, alpha=.3)
p <- ggplot(tr) + geom_tree() + geom_tiplab() 
p2 <- ggtree:::add_panel(p, 'alignment')
p2+aln + theme_tree2()
```

I can write a wrapper function to do these operations (rearrange y axis according to the tree, add dummy facets).

There is an issue, that `geom_alignment` requires `ggplot()` without `aes` mapping. 
For example, if I use `ggtree()`, which is shortcut for `ggplot(aes(x, y)) + geom_tree()`, the following code throw error:

```r
ggtree(tr) + geom_tiplab() -> p
p2 <- ggtree:::add_panel(p, 'alignment')
aln <- geom_alignment(grl3, alpha=.3)
p2+aln
```

```
> p2+aln
Error in eval(expr, envir, enclos) : object 'x' not found
```

This is very easy to solve, if you can add `inherit.aes` parameter to `geom_alignment` and pass it to `geom_rect`, `geom_segment` *etc* that `geom_alignment` called, see <https://guangchuangyu.github.io/ggtree/faq/#inherit-aes>.

If you have any idea to present phylogenetic tree with genomic features, don't hesitate to let me know. We can work it out together to make it more user friendly :).

**Comment by lawremi** [comment]
Hi Guangchuang, 

Tengfei is no longer involved in the project. It seems you understand this stuff better than me, so perhaps you could submit a pull request for the bug? The code for laying out the panels does look tricky, and we could work to simplify it.

One thing you could do is convert the `endoapply` to this:
```
grl3$panel <- factor("alignment", levels=c("TREE", "alignment"))
```
Since the outer mcols should be carried over to the internal data frame.

**Comment by GuangchuangYu** [comment]
Thanks Michael. One question, where should I fork? I can't find ggbio repo in github except the Bioconductor mirror.

**Comment by lawremi** [comment]
I guess it's easiest to fork the GitHub Bioconductor mirror of ggbio and then send me a patch.

**Comment by GuangchuangYu** [comment]
[inherit_aes_patch.txt](https://github.com/tengfei/ggbio/files/552272/inherit_aes_patch.txt)

`inherit.aes=FALSE` can be passed to `geom_alignment` and it will be parsed as `args.non` and also pass to other layers that it called.

The problem here is `args.non` was abandoned except `c("offset", "chevron.height")` when passing to `gap.geom`.

The only change here is:
```
                 args.gaps.extra <- args.non[names(args.non) %in%
-                                            c("offset", "chevron.height")]
+                                            c("offset", "chevron.height", "inherit.aes")]
```

It solved this issue, but I think you may consider to implement a better solution, as there maybe other parameters that are useful and will just be ignored.

**Comment by GuangchuangYu** [comment]
With this patch and github version of ggtree, we can visualize this figure using:

```r
ggtree(tr) + geom_tiplab() -> p
facet_plot(p, 'alignment', grl, geom_alignment, inherit.aes=FALSE, mapping=aes())
```

I also detect another issue in `parseArgsForAes`, which can't parse `mapping=NULL`.

This is why I need to use `mapping=aes()`. I think you need to correct it as `mapping=NULL` is quite common in `ggplot2`.

```r
> facet_plot(p, 'alignment', grl, geom_alignment, inherit.aes=FALSE)
Error in as.vector(y) : attempt to apply non-function
> facet_plot(p, 'alignment', grl, geom_alignment, inherit.aes=FALSE, mapping=aes())
Warning: Ignoring unknown aesthetics: y
```

**Comment by GuangchuangYu** [comment]
BTW: the tricky `facet_plot` function is explained [here](https://guangchuangyu.github.io/2016/10/facet_plot-a-general-solution-to-associate-data-with-phylogenetic-tree/).

**Comment by lawremi** [comment]
Thanks. ggbio 1.23.2 incorporates the patch. I also tried to clean up the aesthetic parsing in biovizBase 1.23.1.
