### ISSUE TITLE
'panel.margin' is deprecated

### ISSUE THREAD

**Issue by twmccart** [tengfei/ggbio#90]
While going through the introductory examples from the ggbio manual, I receive the warning: "`panel.margin` is deprecated. Please use `panel.spacing` property instead"
I assume that a few lines of code need to be updated to keep up with the current version of ggplot2.

**Comment by lawremi** [comment]
Probably. Since the package does not have an active maintainer, perhaps you could submit a pull request with the fix?

**Comment by ivan-krukov** [comment]
@lawremi I would love to fix this. Should the pull request be submitted through `bioconductor`? I'm not familiar with the dev workflow there - can you give me some pointers please?

**Comment by lawremi** [comment]
Probably easiest to just send me the patch (generated e.g. with `svn diff`) by email.

**Comment by zx8754** [comment]
Using `ggbio_1.24.1`, issue is still there.

**Comment by lawremi** [comment]
@ivan-krukov this repository is now synched with Bioconductor, so you could send the fix as PR.

**Comment by lawremi** [comment]
@zx8754 the blue line (rectangle) is the highlight.

**Comment by zx8754** [comment]
@lawremi Thanks you, I understand that, but according to manual that rectangle should appear using `xlim`, too, and it doesn't, so found the way to highlight using `zoom.region`.

**Comment by lawremi** [comment]
Would you please point out where the manual says that `xlim=` should do anything? I see the `+ xlim()` syntax, which should still work. Obviously that's an undesirable inconsistency in the API; unfortunately it's probably not worth the investment in fixing. We are about to rethink and rewrite ggbio.
