### ISSUE TITLE
geom_text using metadata from Granges object?

### ISSUE THREAD

**Issue by nnalpas** [tengfei/ggbio#93]
Hi,
Sorry to ask my question in the issue.
Any chance that ggbio "is/will be" able to display label (via geom_text?) contained as metadata of a Granges object?
Or is there an alternative?
Thanks,

**Comment by lawremi** [comment]
Simplest approach would be to coerce the GRanges to a data.frame with `as.data.frame(gr)` and proceed as normal.

**Comment by nnalpas** [comment]
Of course, should have thought about it. Works perfectly now.
Thanks

**Comment by harbi811** [comment]
> 

Hi @lawremi,
My apologies for commenting on a closed issue. I am trying to label outlier points in the Manhattan point and  I am unsure whether ggbio has an argument for that. Kindly advice on this
