### ISSUE TITLE
plotIdeogram fails on genome hg38

### ISSUE THREAD

**Issue by ramiromagno** [tengfei/ggbio#99]
Running `plotIdeogram` with `genome` set as `"hg38"` yields an error:

```
Error in getIdeogram(genome = genome, subchr = subchr, cytobands = cytobands) : 
  object 'cytobands' not found
```
The issue stems from here:

[line 24 of ideogram.R](https://github.com/tengfei/ggbio/blob/24310c0aee39badda43b15deb6bf872c6d41295c/R/ideogram.R#L24)

The `cytobands = cytobands` should read `cytobands = cytoband`.

**Comment by lawremi** [comment]
Thanks. Want to submit a PR for the credit?

**Comment by ramiromagno** [comment]
No need. Go ahead.
